name: Sync Data
on:
  repository_dispatch:
    types: [sync-data]
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_TOKEN }}
      - name: Update data
        env:
          DATA: ${{ toJSON(github.event.client_payload.data) }}
        run: |
          echo $DATA | python3 -c "import sys,json; print(json.loads(sys.stdin.read()))" > data.json
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add data.json
          git commit -m "Update schedule data" || exit 0
          git push
